language: cpp

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake .. -DGMX_BUILD_OWN_FFTW=ON -DREGRESSIONTEST_DOWNLOAD=ON

script:
  # Build GROMACS
  - make -j4
  # Test
  - make check -j4